// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYTf16FrNaWboyhdRZWdZCu_d4sJjhic',
    appId: '1:124669794800:web:595dae5b46bfb39c93a535',
    messagingSenderId: '124669794800',
    projectId: 'fir-crud-practice-acc0c',
    authDomain: 'fir-crud-practice-acc0c.firebaseapp.com',
    storageBucket: 'fir-crud-practice-acc0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSgf0JsNDDXT1g_sny3UU8BVcl2AvzZIw',
    appId: '1:124669794800:android:98011344884bc8d593a535',
    messagingSenderId: '124669794800',
    projectId: 'fir-crud-practice-acc0c',
    storageBucket: 'fir-crud-practice-acc0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgmRaU-lRqvUTidos-CGUbXivU_juXv5M',
    appId: '1:124669794800:ios:0dab3161eb82c31a93a535',
    messagingSenderId: '124669794800',
    projectId: 'fir-crud-practice-acc0c',
    storageBucket: 'fir-crud-practice-acc0c.appspot.com',
    iosBundleId: 'com.example.firebaseGetsetUserdata',
  );
}
